config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    #renders :show
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    if item.save
      redirect_to items_path
    else 
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       redirect_to items_path
    else
        render :edit
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_path
  end

private
  def item_params
    params.require(:item).permit(:task)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit Task</h1>

<%= form_for @item do |f| %>

  <%= f.label :task %>
  <%= f.text_field :task, placeholder: 'Task', required: true %>
  <br />

  <%= f.submit %>

<% end %>

app/views/items/index.html.erb
<h1>To Do List</h1>
<ol>

  <% @items.each do |item| %>

    <div>
      <li>
        <%= link_to item.task, item_path(item) %>
        <%= link_to 'Edit', edit_item_path(item) %>
        <%= link_to 'Delete', item_path(item), method: :delete %>
      </li>
    </div>

  <%end%>
</ol>

<%= link_to 'New Task', new_item_path %>

app/views/items/new.html.erb
<h1>Create a New Task</h1>

<%= form_for @item do |f| %>

  <%= f.label :task %>
  <%= f.text_field :task, placeholder: 'Task', required: true %>
  <br />

  <%= f.submit %>

<% end %>

app/views/items/show.html.erb
<h1><%= @item.task %></h1>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>